version: 2


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py


# Optionally, you can specify a custom build command
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

  commands:
    - git submodule update --init --recursive
    - python3 -m pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - poetry run sphinx-build -b html docs _readthedocs/html/
